name: Rust development check

on:
  push:
    branches: [ "!master" ]
  pull_request:
    branches: [ "!master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose
  beta:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - beta

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose
  nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - uses: actions/checkout@v3
    - name: Setup compiler
      run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Check
      run: cargo check --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run formatter
      run: cargo fmt -- --check --verbose